Created the basic text-image container
PALSVitcc/pals-website pull request #2
Opened 2020-07-30 16:45 UTC by PratikGarai

The container having image and text side by side + responsive css

2020-07-30 16:51 UTC, manakpandey requested changes
Try to make use of bootstrap as much as you can.

2020-07-30 16:51 UTC, manakpandey commented on index.html
> +	<main>
remove ```main``` tag

2020-07-30 16:51 UTC, manakpandey commented on index.html
> +				<div class="half d-md-flex d-block align-items-stretch">
Try using the grid in bootstrap, instead of writing css yourself.

2020-07-30 18:41 UTC, PratikGarai commented
Made the changes. Also added an hr tag to enhance readability in responsive mode when the width is reduced.
![image](https://user-images.githubusercontent.com/58355527/88961215-52088580-d2c2-11ea-878c-4ed9a5c327b5.png)
As the width reduces, the alternate occurring text fields appear together.

2020-07-30 18:54 UTC, manakpandey requested changes

2020-07-30 18:54 UTC, manakpandey commented on index.html
> +	<hr>
remove ```hr``` and add margin instead

2020-07-31 05:34 UTC, PratikGarai commented
Added the footer's basic structure. Icons for social media left.

2020-08-01 14:43 UTC, closed without merging